# Generated by Django 4.1.3 on 2022-11-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tittle',
            new_name='title',
        ),
    ]
