# Generated by Django 4.1.3 on 2022-11-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_tittle_hashtag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
